### PR TITLE
Test_Grafana_plugins_provisioning

### PR DESCRIPTION
**Pull request by darshank15**

### CODE REVIEW

**Comment by darshank15** [comment]
When I and Bart working on the Grafana plugin issue, This branch we created only for testing. Nothing meaningful here. Idealy we should not merge it to the main repo.

**Comment by NicolasToussaint** [comment]
> When I and Bart working on the Grafana plugin issue, This branch we created only for testing. Nothing meaningful here. Idealy we should not merge it to the main repo.

oh, should I un-merge this entirely ?

**Comment by darshank15** [comment]
Yes, this branch needs to un-merged.

**Comment by darshank15** [comment]
As plugin installation is included branch1, Here https://github.com/Orange-OpenSource/fossdash/pull/1/commits/34b366f0f7fd9ef75392eb16e0f2dc7ebf8e796d

**Pull request merged**
